#include "dak/six_eight/tile.h"


namespace dak::six_eight
{
   ////////////////////////////////////////////////////////////////////////////
   //
   // A tile.
   //
   // Can be rotated. Two tiles are the same if they match under some rotation.

   std::map<char, tile_description_t> tile_t::tile_by_ids =
   {
      { 0, { } },
      { 'a', {
          position_t(0, 0),
          position_t(1, 0),
          position_t(2, 0),
          position_t(2, 1),
          position_t(2, 2),
          position_t(2, 3),
      }},
      { 'A', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 0),
          position_t(2, 0),
      }},
      { 'b', {
          position_t(0, 2),
          position_t(0, 3),
          position_t(0, 4),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
      }},
      { 'B', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 2),
          position_t(1, 3),
          position_t(1, 4),
      }},
      { 'c', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 3),
      }},
      { 'd', {
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
      }},
      { 'e', {
          position_t(0, 2),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 0),
      }},
      { 'E', {
          position_t(0, 0),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 2),
      }},
      { 'f', {
          position_t(0, 1),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 0),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { 'F', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 2),
      }},
      { 'g', {
          position_t(0, 0),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
      }},
      { 'G', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 0),
          position_t(1, 2),
          position_t(1, 3),
      }},
      { 'h', {
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 2),
          position_t(2, 0),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { 'H', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 2),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { 'i', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 2),
      }},
      { 'I', {
          position_t(0, 0),
          position_t(0, 2),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
      }},
      { 'j', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(0, 4),
          position_t(1, 4),
      }},
      { 'J', {
          position_t(0, 4),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(1, 4),
      }},
      { 'k', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 3),
      }},
      { 'K', {
          position_t(0, 3),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 0),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { 'l', {
          position_t(0, 1),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { 'm', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(1, 0),
          position_t(1, 1),
          position_t(2, 0),
          position_t(2, 1),
      }},
      { 'n', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
      }},
      { 'N', {
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
      }},
      { 'o', {
          position_t(0, 2),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 1),
      }},
      { 'O', {
          position_t(0, 1),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 2),
      }},
      { 'p', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(0, 4),
          position_t(1, 2),
      }},
      { 'q', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 2),
          position_t(1, 3),
      }},
      { 'Q', {
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
      }},
      { 'r', {
          position_t(0, 1),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(1, 4),
      }},
      { 'R', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(0, 4),
          position_t(1, 1),
      }},
      { 's', {
          position_t(0, 0),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { 'S', {
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 0),
      }},
      { 't', {
          position_t(0, 0),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 0),
      }},
      { 'u', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 2),
      }},
      { 'v', {
          position_t(0, 1),
          position_t(1, 0),
          position_t(1, 1),
          position_t(2, 2),
          position_t(1, 3),
          position_t(2, 1),
      }},
      { 'w', {
          position_t(0, 1),
          position_t(1, 1),
          position_t(2, 0),
          position_t(2, 1),
          position_t(2, 2),
          position_t(2, 3),
      }},
      { 'W', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 1),
          position_t(2, 1),
      }},
      { 'x', {
          position_t(0, 2),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 3),
      }},
      { 'X', {
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 2),
      }},
      { 'y', {
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(0, 4),
          position_t(1, 0),
          position_t(1, 1),
      }},
      { 'Y', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(1, 4),
      }},
      { 'z', {
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 1),
          position_t(2, 0),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { 'Z', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 1),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { '1', {
          position_t(0, 1),
          position_t(1, 0),
          position_t(1, 1),
          position_t(2, 1),
          position_t(2, 2),
          position_t(2, 3),
      }},
      { '!', {
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 1),
          position_t(2, 1),
      }},
      { '2', {
          position_t(0, 0),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 2),
          position_t(2, 3),
      }},
      { '@', {
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 0),
      }},
      { '3', {
          position_t(0, 1),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 0),
          position_t(2, 1),
      }},
      { '#', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 1),
      }},
      { '4', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(1, 1),
          position_t(2, 1),
          position_t(2, 2),
          position_t(2, 3),
      }},
      { '$', {
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 1),
          position_t(2, 0),
          position_t(2, 1),
      }},
      { '5', {
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 0),
          position_t(1, 1),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { '6', {
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 0),
          position_t(2, 1),
      }},
      { '^', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 2),
          position_t(2, 3),
      }},
      { '7', {
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 0),
      }},
      { '&', {
          position_t(0, 0),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 3),
      }},
      { '8', {
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(0, 4),
          position_t(0, 5),
      }},
      { '9', {
          position_t(0, 1),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 0),
          position_t(2, 1),
          position_t(3, 0),
      }},
      { '(', {
          position_t(0, 0),
          position_t(1, 0),
          position_t(1, 1),
          position_t(2, 1),
          position_t(2, 2),
          position_t(3, 1),
      }},
   };

   tile_description_t tile_t::get_positions() const
   {
      tile_description_t positions = tile_by_ids[my_id];
      int min_x = 1000;
      int min_y = 1000;
      for (position_t& pos : positions.block_positions)
      {
         pos.rotate_in_place(my_rotation);
         min_x = std::min(min_x, pos.x());
         min_y = std::min(min_y, pos.y());
      }

      for (position_t& pos : positions.block_positions)
      {
         pos = pos.move(-min_x, -min_y);
      }

      std::sort(positions.block_positions, positions.block_positions + 6);

      return positions;
   }

}
